# Generated by Django 5.1.3 on 2024-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_class_max_students_class_password_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('identification', 'Identification'), ('multiple choice', 'Multiple Choice'), ('enumeration', 'Enumeration'), ('true or false', 'True or False')], max_length=50),
        ),
    ]
