# Generated by Django 5.1.3 on 2025-01-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_question_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='quiz_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='student_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='response',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='student_answer',
            field=models.TextField(),
        ),
    ]
